steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/venture-lab-1/chatgpt-retrieval-plugin/chatgpt-retrieval-plugin", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/venture-lab-1/chatgpt-retrieval-plugin/chatgpt-retrieval-plugin"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "chatgpt-retrieval-plugin",
        "--image",
        "gcr.io/venture-lab-1/chatgpt-retrieval-plugin/chatgpt-retrieval-plugin",
        "--region",
        "us-west1",
      ]
images:
  - gcr.io/venture-lab-1/chatgpt-retrieval-plugin/chatgpt-retrieval-plugin
